use pchardware;



insert into gpu_chips values
                          (null, 1, 'Aldebaran'),
                          (null, 1, 'Amethyst'),
                          (null, 1, 'Antigua'),
                          (null, 1, 'Antilles'),
                          (null, 1, 'Aqua Vanjaram'),
                          (null, 1, 'Arcturus'),
                          (null, 1, 'Baffin'),
                          (null, 1, 'Banded Kestrel'),
                          (null, 1, 'Banks'),
                          (null, 1, 'Barcelo'),
                          (null, 1, 'Barts'),
                          (null, 1, 'Beema'),
                          (null, 1, 'Blackcomb'),
                          (null, 1, 'Bonaire'),
                          (null, 1, 'Broadway'),
                          (null, 1, 'Caicos'),
                          (null, 1, 'Cape Verde'),
                          (null, 1, 'Capilano'),
                          (null, 1, 'Capsaicin'),
                          (null, 1, 'Cayman'),
                          (null, 1, 'Cedar'),
                          (null, 1, 'Cezanne'),
                          (null, 1, 'Cezanne-M'),
                          (null, 1, 'Chelsea'),
                          (null, 1, 'Curacao'),
                          (null, 1, 'Cypress'),
                          (null, 1, 'Devastator'),
                          (null, 1, 'Devastator Lite'),
                          (null, 1, 'Dragon Range'),
                          (null, 1, 'Durango'),
                          (null, 1, 'Durango 2'),
                          (null, 1, 'Ellesmere'),
                          (null, 1, 'Emerald'),
                          (null, 1, 'Exo'),
                          (null, 1, 'Fiji'),
                          (null, 1, 'Granville'),
                          (null, 1, 'Grenada'),
                          (null, 1, 'Hawaii'),
                          (null, 1, 'Heathrow'),
                          (null, 1, 'Jet'),
                          (null, 1, 'Juniper'),
                          (null, 1, 'Kalindi'),
                          (null, 1, 'Kryptos'),
                          (null, 1, 'Latte'),
                          (null, 1, 'Lexa'),
                          (null, 1, 'Lexington'),
                          (null, 1, 'Litho'),
                          (null, 1, 'Liverpool'),
                          (null, 1, 'Liverpool 16nm'),
                          (null, 1, 'Lockhart'),
                          (null, 1, 'Loveland'),
                          (null, 1, 'Lucienne'),
                          (null, 1, 'Malta'),
                          (null, 1, 'Mars'),
                          (null, 1, 'Mendocino'),
                          (null, 1, 'Meso'),
                          (null, 1, 'Navi 10'),
                          (null, 1, 'Navi 12'),
                          (null, 1, 'Navi 14'),
                          (null, 1, 'Navi 21'),
                          (null, 1, 'Navi 22'),
                          (null, 1, 'Navi 23'),
                          (null, 1, 'Navi 24'),
                          (null, 1, 'Navi 31'),
                          (null, 1, 'Navi 32'),
                          (null, 1, 'Navi 33'),
                          (null, 1, 'Neo'),
                          (null, 1, 'Neptune'),
                          (null, 1, 'New Zealand'),
                          (null, 1, 'Oberon'),
                          (null, 1, 'Oberon Plus'),
                          (null, 1, 'Oland'),
                          (null, 1, 'Onega'),
                          (null, 1, 'Opal'),
                          (null, 1, 'Park'),
                          (null, 1, 'Phoenix'),
                          (null, 1, 'Picasso'),
                          (null, 1, 'Picasso-M'),
                          (null, 1, 'Pinewood'),
                          (null, 1, 'Pitcairn'),
                          (null, 1, 'Polaris 20'),
                          (null, 1, 'Polaris 21'),
                          (null, 1, 'Polaris 23'),
                          (null, 1, 'Polaris 24'),
                          (null, 1, 'Polaris 31'),
                          (null, 1, 'R580'),
                          (null, 1, 'RV670'),
                          (null, 1, 'RV711'),
                          (null, 1, 'RV770'),
                          (null, 1, 'Raphael'),
                          (null, 1, 'Raven-M'),
                          (null, 1, 'Redwood'),
                          (null, 1, 'Rembrandt'),
                          (null, 1, 'Rembrandt+'),
                          (null, 1, 'Renoir'),
                          (null, 1, 'Renoir-M'),
                          (null, 1, 'Robson'),
                          (null, 1, 'Saturn'),
                          (null, 1, 'Scarlett'),
                          (null, 1, 'Scorpio'),
                          (null, 1, 'Scrapper'),
                          (null, 1, 'Scrapper Lite'),
                          (null, 1, 'Sephiroth'),
                          (null, 1, 'Spectre'),
                          (null, 1, 'Spectre Lite'),
                          (null, 1, 'Spectre SL'),
                          (null, 1, 'Stoney'),
                          (null, 1, 'Strato'),
                          (null, 1, 'Sumo'),
                          (null, 1, 'Sun'),
                          (null, 1, 'SuperSumo'),
                          (null, 1, 'Tahiti'),
                          (null, 1, 'Thames'),
                          (null, 1, 'Tobago'),
                          (null, 1, 'Trinidad'),
                          (null, 1, 'Tropo'),
                          (null, 1, 'Turks'),
                          (null, 1, 'Van Gogh'),
                          (null, 1, 'Vega 10'),
                          (null, 1, 'Vega 20'),
                          (null, 1, 'Venus'),
                          (null, 1, 'Vesuvius'),
                          (null, 1, 'Wani'),
                          (null, 1, 'Weston'),
                          (null, 1, 'Whistler'),
                          (null, 1, 'Wimbledon'),
                          (null, 1, 'Seymour'),
                          (null, 1, 'Tonga'),
                          (null, 1, 'Topaz'),
                          (null, 2, 'AD102'),
                          (null, 2, 'AD103'),
                          (null, 2, 'AD104'),
                          (null, 2, 'AD106'),
                          (null, 2, 'AD107'),
                          (null, 2, 'C51'),
                          (null, 2, 'C67'),
                          (null, 2, 'C73'),
                          (null, 2, 'C77'),
                          (null, 2, 'C78'),
                          (null, 2, 'C79'),
                          (null, 2, 'C7A'),
                          (null, 2, 'C7A-ION'),
                          (null, 2, 'C89'),
                          (null, 2, 'Crush11'),
                          (null, 2, 'Crush17'),
                          (null, 2, 'EXK107'),
                          (null, 2, 'EXMF104'),
                          (null, 2, 'G70'),
                          (null, 2, 'G71'),
                          (null, 2, 'G73B'),
                          (null, 2, 'G80'),
                          (null, 2, 'G84'),
                          (null, 2, 'G86'),
                          (null, 2, 'G86S'),
                          (null, 2, 'G92'),
                          (null, 2, 'G92B'),
                          (null, 2, 'G94'),
                          (null, 2, 'G94B'),
                          (null, 2, 'G96'),
                          (null, 2, 'G96B'),
                          (null, 2, 'G96C'),
                          (null, 2, 'G98'),
                          (null, 2, 'G98S'),
                          (null, 2, 'GA100'),
                          (null, 2, 'GA102'),
                          (null, 2, 'GA103'),
                          (null, 2, 'GA104'),
                          (null, 2, 'GA106'),
                          (null, 2, 'GA107'),
                          (null, 2, 'GA107S'),
                          (null, 2, 'GA107SB'),
                          (null, 2, 'GA10B'),
                          (null, 2, 'GB100'),
                          (null, 2, 'GF100'),
                          (null, 2, 'GF104'),
                          (null, 2, 'GF106'),
                          (null, 2, 'GF108'),
                          (null, 2, 'GF110'),
                          (null, 2, 'GF114'),
                          (null, 2, 'GF116'),
                          (null, 2, 'GF116S'),
                          (null, 2, 'GF117'),
                          (null, 2, 'GF117B'),
                          (null, 2, 'GF119'),
                          (null, 2, 'GF119S'),
                          (null, 2, 'GH100'),
                          (null, 2, 'GK104'),
                          (null, 2, 'GK106'),
                          (null, 2, 'GK106S'),
                          (null, 2, 'GK107'),
                          (null, 2, 'GK110'),
                          (null, 2, 'GK110B'),
                          (null, 2, 'GK180'),
                          (null, 2, 'GK208'),
                          (null, 2, 'GK208B'),
                          (null, 2, 'GK20A'),
                          (null, 2, 'GK210'),
                          (null, 2, 'GM107'),
                          (null, 2, 'GM108'),
                          (null, 2, 'GM108S'),
                          (null, 2, 'GM200'),
                          (null, 2, 'GM204'),
                          (null, 2, 'GM206'),
                          (null, 2, 'GM206S'),
                          (null, 2, 'GM20B'),
                          (null, 2, 'GP100'),
                          (null, 2, 'GP102'),
                          (null, 2, 'GP104'),
                          (null, 2, 'GP104B'),
                          (null, 2, 'GP106'),
                          (null, 2, 'GP107'),
                          (null, 2, 'GP107S'),
                          (null, 2, 'GP108'),
                          (null, 2, 'GP108B'),
                          (null, 2, 'GP10B'),
                          (null, 2, 'GT200'),
                          (null, 2, 'GT200B'),
                          (null, 2, 'GT215'),
                          (null, 2, 'GT216'),
                          (null, 2, 'GT218'),
                          (null, 2, 'GT218S'),
                          (null, 2, 'GV100'),
                          (null, 2, 'GV10B'),
                          (null, 2, 'ION'),
                          (null, 2, 'Kal-El'),
                          (null, 2, 'NV1'),
                          (null, 2, 'NV10'),
                          (null, 2, 'NV11'),
                          (null, 2, 'NV11B'),
                          (null, 2, 'NV15'),
                          (null, 2, 'NV17'),
                          (null, 2, 'NV18'),
                          (null, 2, 'NV18C'),
                          (null, 2, 'NV20'),
                          (null, 2, 'NV25'),
                          (null, 2, 'NV28'),
                          (null, 2, 'NV2A'),
                          (null, 2, 'NV3'),
                          (null, 2, 'NV30'),
                          (null, 2, 'NV31'),
                          (null, 2, 'NV34'),
                          (null, 2, 'NV34B'),
                          (null, 2, 'NV35'),
                          (null, 2, 'NV36'),
                          (null, 2, 'NV36B'),
                          (null, 2, 'NV36S'),
                          (null, 2, 'NV37'),
                          (null, 2, 'NV38'),
                          (null, 2, 'NV39'),
                          (null, 2, 'NV4'),
                          (null, 2, 'NV40'),
                          (null, 2, 'NV41'),
                          (null, 2, 'NV43'),
                          (null, 2, 'NV44'),
                          (null, 2, 'NV45'),
                          (null, 2, 'NV48'),
                          (null, 2, 'NV5'),
                          (null, 2, 'RSX-28nm'),
                          (null, 2, 'RSX-40nm'),
                          (null, 2, 'RSX-65nm'),
                          (null, 2, 'Tegra 2'),
                          (null, 2, 'TU102'),
                          (null, 2, 'TU104'),
                          (null, 2, 'TU104B'),
                          (null, 2, 'TU106'),
                          (null, 2, 'TU106B'),
                          (null, 2, 'TU116'),
                          (null, 2, 'TU117'),
                          (null, 2, 'TU117S'),
                          (null, 2, 'TU117SB'),
                          (null, 2, 'Wayne'),
                          (null, 3, 'Alder Lake GT1'),
                          (null, 3, 'Almador'),
                          (null, 3, 'Alviso'),
                          (null, 3, 'Arctic Sound'),
                          (null, 3, 'Auburn'),
                          (null, 3, 'Bearlake'),
                          (null, 3, 'Broadwater'),
                          (null, 3, 'Brookdale'),
                          (null, 3, 'Calistoga'),
                          (null, 3, 'Cantiga'),
                          (null, 3, 'Cedarview'),
                          (null, 3, 'Cloverview'),
                          (null, 3, 'Crestline'),
                          (null, 3, 'DG2-128'),
                          (null, 3, 'DG2-256'),
                          (null, 3, 'DG2-512'),
                          (null, 3, 'Eaglelake'),
                          (null, 3, 'Grantsdale'),
                          (null, 3, 'Ironlake'),
                          (null, 3, 'Jasper Lake GT1'),
                          (null, 3, 'Knights Ferry'),
                          (null, 3, 'Lakeport'),
                          (null, 3, 'Lincroft'),
                          (null, 3, 'Meteor Lake GT1'),
                          (null, 3, 'Montara'),
                          (null, 3, 'Montevina'),
                          (null, 3, 'Pineview'),
                          (null, 3, 'Ponte Vecchio'),
                          (null, 3, 'Portola'),
                          (null, 3, 'Poulsbo'),
                          (null, 3, 'Raptor Lake GT1'),
                          (null, 3, 'Rialto Bridge'),
                          (null, 3, 'Rocket Lake GT1'),
                          (null, 3, 'Sandy Bridge GT1'),
                          (null, 3, 'Sandy Bridge GT2'),
                          (null, 3, 'Sandy Bridge GT2+'),
                          (null, 3, 'Solano'),
                          (null, 3, 'Springdale'),
                          (null, 3, 'Tiger Lake GT1'),
                          (null, 3, 'Whitney')
;