use pchardware;

insert into gpu_chips values
                          (null, 1, 'Aldebaran'),
                          (null, 1, 'Amethyst'),
                          (null, 1, 'Antigua'),
                          (null, 1, 'Antilles'),
                          (null, 1, 'Aqua Vanjaram'),
                          (null, 1, 'Arcturus'),
                          (null, 1, 'Baffin'),
                          (null, 1, 'Banded Kestrel'),
                          (null, 1, 'Banks'),
                          (null, 1, 'Barcelo'),
                          (null, 1, 'Barts'),
                          (null, 1, 'Beema'),
                          (null, 1, 'Blackcomb'),
                          (null, 1, 'Bonaire'),
                          (null, 1, 'Broadway'),
                          (null, 1, 'Caicos'),
                          (null, 1, 'Cape Verde'),
                          (null, 1, 'Capilano'),
                          (null, 1, 'Capsaicin'),
                          (null, 1, 'Cayman'),
                          (null, 1, 'Cedar'),
                          (null, 1, 'Cezanne'),
                          (null, 1, 'Cezanne-M'),
                          (null, 1, 'Chelsea'),
                          (null, 1, 'Curacao'),
                          (null, 1, 'Cypress'),
                          (null, 1, 'Devastator'),
                          (null, 1, 'Devastator Lite'),
                          (null, 1, 'Dragon Range'),
                          (null, 1, 'Durango'),
                          (null, 1, 'Durango 2'),
                          (null, 1, 'Ellesmere'),
                          (null, 1, 'Emerald'),
                          (null, 1, 'Exo'),
                          (null, 1, 'Fiji'),
                          (null, 1, 'Granville'),
                          (null, 1, 'Grenada'),
                          (null, 1, 'Hawaii'),
                          (null, 1, 'Heathrow'),
                          (null, 1, 'Jet'),
                          (null, 1, 'Juniper'),
                          (null, 1, 'Kalindi'),
                          (null, 1, 'Kryptos'),
                          (null, 1, 'Latte'),
                          (null, 1, 'Lexa'),
                          (null, 1, 'Lexington'),
                          (null, 1, 'Litho'),
                          (null, 1, 'Liverpool'),
                          (null, 1, 'Liverpool 16nm'),
                          (null, 1, 'Lockhart'),
                          (null, 1, 'Loveland'),
                          (null, 1, 'Lucienne'),
                          (null, 1, 'Malta'),
                          (null, 1, 'Mars'),
                          (null, 1, 'Mendocino'),
                          (null, 1, 'Meso'),
                          (null, 1, 'Navi 10'),
                          (null, 1, 'Navi 12'),
                          (null, 1, 'Navi 14'),
                          (null, 1, 'Navi 21'),
                          (null, 1, 'Navi 22'),
                          (null, 1, 'Navi 23'),
                          (null, 1, 'Navi 24'),
                          (null, 1, 'Navi 31'),
                          (null, 1, 'Navi 32'),
                          (null, 1, 'Navi 33'),
                          (null, 1, 'Neo'),
                          (null, 1, 'Neptune'),
                          (null, 1, 'New Zealand'),
                          (null, 1, 'Oberon'),
                          (null, 1, 'Oberon Plus'),
                          (null, 1, 'Oland'),
                          (null, 1, 'Onega'),
                          (null, 1, 'Opal'),
                          (null, 1, 'Park'),
                          (null, 1, 'Phoenix'),
                          (null, 1, 'Picasso'),
                          (null, 1, 'Picasso-M'),
                          (null, 1, 'Pinewood'),
                          (null, 1, 'Pitcairn'),
                          (null, 1, 'Polaris 20'),
                          (null, 1, 'Polaris 21'),
                          (null, 1, 'Polaris 23'),
                          (null, 1, 'Polaris 24'),
                          (null, 1, 'Polaris 31'),
                          (null, 1, 'R580'),
                          (null, 1, 'RV670'),
                          (null, 1, 'RV711'),
                          (null, 1, 'RV770'),
                          (null, 1, 'Raphael'),
                          (null, 1, 'Raven-M'),
                          (null, 1, 'Redwood'),
                          (null, 1, 'Rembrandt'),
                          (null, 1, 'Rembrandt+'),
                          (null, 1, 'Renoir'),
                          (null, 1, 'Renoir-M'),
                          (null, 1, 'Robson'),
                          (null, 1, 'Saturn'),
                          (null, 1, 'Scarlett'),
                          (null, 1, 'Scorpio'),
                          (null, 1, 'Scrapper'),
                          (null, 1, 'Scrapper Lite'),
                          (null, 1, 'Sephiroth'),
                          (null, 1, 'Spectre'),
                          (null, 1, 'Spectre Lite'),
                          (null, 1, 'Spectre SL'),
                          (null, 1, 'Stoney'),
                          (null, 1, 'Strato'),
                          (null, 1, 'Sumo'),
                          (null, 1, 'Sun'),
                          (null, 1, 'SuperSumo'),
                          (null, 1, 'Tahiti'),
                          (null, 1, 'Thames'),
                          (null, 1, 'Tobago'),
                          (null, 1, 'Trinidad'),
                          (null, 1, 'Tropo'),
                          (null, 1, 'Turks'),
                          (null, 1, 'Van Gogh'),
                          (null, 1, 'Vega 10'),
                          (null, 1, 'Vega 20'),
                          (null, 1, 'Venus'),
                          (null, 1, 'Vesuvius'),
                          (null, 1, 'Wani'),
                          (null, 1, 'Weston'),
                          (null, 1, 'Whistler'),
                          (null, 1, 'Wimbledon'),
                          (null, 1, 'Seymour'),
                          (null, 1, 'Tonga'),
                          (null, 1, 'Topaz'),
                          (null, 2, '')
;
